db_url = "replaceme"
kvs_url = "replaceme"
server_addr = "replaceme"
server_bind = "replaceme"
admin_name = "kotosiro"
admin_email = "kotosiro@email.com"
admin_password = "password"
admin_namespace = "admin"
admin_ttl = 28800
jwt_secret = "your secret here"
gcp_sa_private_key = "creds/gcp/sa-private-key.json"
aws_credentials = "creds/aws/credentials"
aws_profile = "kotosiro-sharing"
swagger_ui_path = "/swagger"
open_api_doc_path = "/api-doc/openapi.json"
use_json_log = false
log_filter = "warn,kotosiro_sharing=info"