db_url = "replaceme"
kvs_url = "replaceme"
server_addr = "replaceme"
server_bind = "replaceme"
jwt_secret = "your secret here"
jwt_expiration_sec = 28800
gcp_sa_private_key = "creds/gcp/sa-private-key.json"
aws_credentials = "creds/aws/credentials"
aws_profile = "kotosiro-sharing"
use_json_log = false
log_filter = "warn,kotosiro_sharing=info"