[package]
name = "kotosiro-sharing"
version = "0.1.0"
authors = ["Shingo OKAWA <shingo.okawa.g.h.c@gmail.com>"]
edition = "2021"
rust-version = "1.67"

[dependencies]
argon2 = "0.5.0"
anyhow = { version = "1.0.69", features = ["backtrace"] }
async-session = "3.0.0"
async-trait = "0.1.64"
axum = { version = "0.6.7", features = ["headers"] }
clap = "4.1.4"
tokio = { version = "1.25.0", features = [ "full", "rt-multi-thread" ] }
tower = { version = "0.4.13", features = ["limit", "filter", "util"] }
config = "0.13.3"
chrono = { version = "0.4.23", features = ["serde"] }
colored = "2.0.0"
cookie = "0.17.0"
getset = "0.1.2"
glob = "0.3.1"
git-version = "0.3.5"
jsonwebtoken = "8.3.0"
once_cell = "1.17.1"
rand = "0.8.5"
redis = { version = "0.22.3", features = ["aio", "async-std-comp", "tokio-comp"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.92"
serde_yaml = "0.9.17"
sqlx = { version = "0.6.2", features = ["postgres", "chrono", "uuid", "json", "runtime-tokio-rustls", "migrate"] }
strum = { version = "0.24.1", features = ["derive"] }
strum_macros = "0.24.1"
tracing = "0.1.37"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "json"] }
uuid = { version = "1.3.0", features = [ "v4", "serde" ] }
validator = { version = "0.16.0", features = ["derive"] }

[dev-dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
dotenv = "0.15.0"
futures = "0.3.26"
serial_test = "0.4.0"
testutils = { path = "testutils" }
testcontainers = "0.14.0"