db_url = "postgres://postgres:secret@127.0.0.1:5432/kotosiro_sharing"
server_addr = "http://127.0.0.1:8080"
server_bind = "127.0.0.1:8080"
use_json_log = false
log_filter = "warn,kotosiro_sharing=debug"