db_url = "postgres://postgres:secret@127.0.0.1:5432/kotosiro_sharing"
kvs_url = "redis://127.0.0.1:6379/"
server_addr = "http://127.0.0.1:8080"
server_bind = "127.0.0.1:8080"
admin_name = "kotosiro"
admin_email = "kotosiro@email.com"
admin_password = "password"
admin_namespace = "admin"
jwt_secret = "your secret here"
jwt_expiration_sec = 28800
gcp_sa_private_key = "creds/gcp/sa-private-key.json"
aws_credentials = "creds/aws/credentials"
aws_profile = "kotosiro-sharing"
use_json_log = false
log_filter = "warn,kotosiro_sharing=debug"