version: "3.9"
services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=kotosiro_sharing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
